name: A workflow to deploy the project on Heroku
on: push
jobs:
  setup-ruby:
    name: Deploy APP
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - name:
        Install gem for Ruby
      run:
        gem install dpl
    - name:
        Start Deployment
      run:
        dpl --provider=heroku --app=${{secret.HEROKU_APP_NAME}} --api-key=${{secret.HEROKU_API_KEY}}
